/// go_router 경로 상수
abstract final class RoutePaths {
  static const onboarding = '/onboarding';
  static const onboardingStudent = '/onboarding/student';
  static const onboardingTutor = '/onboarding/tutor';
  static const onboardingPermissions = '/onboarding/permissions';
  static const login = '/login';
  static const signup = '/signup';
  static const signupStudent = '/signup/student';
  static const signupTutor = '/signup/tutor';
  static const passwordReset = '/password-reset';
  static const studentHome = '/student';
  static const studentCreditRecharge = '/student/credit-recharge';
  static const studentSubscription = '/student/subscription';
  static const studentMyReviews = '/student/my-reviews';
  static const studentMyReports = '/student/my-reports';
  static const studentProfileEdit = '/student/profile-edit';
  static const studentProblemUpload = '/student/problem-upload';
  static const studentProblemList = '/student/problem-list';
  static const studentTutorSelection = '/student/tutor-selection';
  static const studentTutorProfile = '/student/tutor-profile';
  static const studentClassroom = '/student/classroom';
  static const studentReviewWrite = '/student/review-write';
  static const studentReport = '/student/report';
  static const tutorLessonComplete = '/tutor/lesson-complete';
  static const tutorHome = '/tutor';
  static const tutorProfileEdit = '/tutor/profile-edit';
  static const tutorAcademicEdit = '/tutor/academic-edit';
  static const tutorMyReviews = '/tutor/my-reviews';
  static const tutorMyReports = '/tutor/my-reports';
}
